# Generated by Django 4.0 on 2022-08-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrandsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la Marca')),
                ('image', models.CharField(max_length=255, verbose_name='URL de la Imágen')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('state', models.BooleanField(default=True, verbose_name='¿Mostrar?')),
            ],
        ),
        migrations.CreateModel(
            name='CountriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='País')),
                ('flag', models.CharField(max_length=255, verbose_name='URL de la Imágen')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('state', models.BooleanField(default=True, verbose_name='¿Mostrar?')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255, unique=True, verbose_name='Modelo del Auto')),
                ('description', models.CharField(max_length=255, verbose_name='Breve Descripción del Auto')),
                ('image', models.CharField(max_length=255, verbose_name='URL de la Imágen')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('state', models.BooleanField(default=True, verbose_name='¿Mostrar?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.carbrandsmodel', verbose_name='Marca Perteneciente')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.countriesmodel', verbose_name='País de Origen')),
            ],
        ),
        migrations.AddField(
            model_name='carbrandsmodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.countriesmodel', verbose_name='País de Origen'),
        ),
    ]
