# Generated by Django 4.0 on 2022-11-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListModel',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Tarea')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Tarea')),
                ('completed', models.BooleanField(default=True, verbose_name='¿Completada?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
            ],
            options={
                'verbose_name': 'Lista de Tarea',
                'verbose_name_plural': 'Lista de Tareas',
                'db_table': 'Lista de Tareas',
            },
        ),
    ]
