# Generated by Django 4.0 on 2022-12-04 19:27

import BaseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Tarea')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, validators=[BaseApp.models.validate_description], verbose_name='Descripción de la Tarea')),
                ('completed', models.BooleanField(default=True, verbose_name='¿Completada?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'lista_de_tareas',
            },
        ),
    ]
