# Generated by Django 4.0 on 2022-11-16 19:12

import BaseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[BaseApp.models.validate_description], verbose_name='Descripción de la Tarea'),
        ),
    ]
